version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=user
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
  
  sarcng-api-image:
    environment:
      NODE_ENV: production
    image: matheuspozzer/sarcng-api-image:latest
    command: node dist/main
    ports:
      - "3333:3000"
    volumes:
      - node-test:/usr/app

volumes:
  data:
  node-test: