name: github-ci.yml
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/sarcng-api-image

          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          docker push ${{ secrets.DOCKER_USERNAME }}/sarcng-api-image:latest

  EC2-Deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ASIAVM4F32DWYNKXJZOZ
      AWS_SECRET_ACCESS_KEY: IC0FRDTQCDTDikuUrnMrqSLfxA7VLkgQSL/53LKR
      AWS_REGION: us-east-1
      AWS-SESSION-TOKEN: >-
        FwoGZXIvYXdzEJD//////////wEaDJ5UUxzuijOjI/B6XCLMAR9Yths87J655gPQTmGQhpz6MNsXXcgKoUH2C+naVRm5MomBl+CsZt5n1dM0pGxdLonNzgL/2A94hSKinzV9PGF9Kn16vf2aSouqrYyQQMxaMaBzJQ+9UL8YDGvJOvO193yWKz/DPNPceKZG2GyvNAu5wuzQ6qs20ZeA8rq6SeyDZLN8J2Hdlf9GSylkIzMjAeSplRoC8tuIImLbYFORdCRxTOGmXBMPQjtJ1GmR4oulhWuIft22rb7ulK4N2+qiXpfbQLn1lj4VBMXdtCiqkpmkBjItCIhE+DcryEGge6F2GlQoPOnvY5GbxugB/BbPeWGRzjZp9+6Y+feRKX5//i0U

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ env.AWS_ACCESS_KEY_ID }}'
          aws-session-token: '${{ env.AWS-SESSION-TOKEN }}'
          aws-secret-access-key: '${{ env.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ env.AWS_REGION }}'

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      # - name: Copy SSH key to runner
      #   run: echo "${{ secrets.AWS_SECRET_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Write EC2 Key Pair to File
        run: 'echo "${{ secrets.AWS_SECRET_KEY }}" > key.pem'

      - name: Set Permissions on Key Pair File
        run: chmod 600 key.pem

      - name: Deploy Docker image to EC2
        run: >
          SSH="ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-3-94-90-15.compute-1.amazonaws.com"

          $SSH "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}"

          $SSH "docker pull ${{ secrets.DOCKER_USERNAME }}/sarcng-api-image:latest"

          $SSH "cd sarcng-api-node && docker-compose down"

          $SSH "cd sarcng-api-node && docker-compose up"
